# Generated by Django 4.2.6 on 2025-09-15 00:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="顧客名")),
                ("phone", models.CharField(max_length=20, verbose_name="電話番号")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="メールアドレス"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="住所")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "顧客",
                "verbose_name_plural": "顧客",
            },
        ),
        migrations.CreateModel(
            name="ProjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="工種名"),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
            ],
            options={
                "verbose_name": "工種",
                "verbose_name_plural": "工種",
            },
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="作業員名")),
                ("phone", models.CharField(max_length=20, verbose_name="電話番号")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="メールアドレス"
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=0, max_digits=8, verbose_name="時給"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="稼働可能")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True, to="projects.projecttype", verbose_name="対応可能工種"
                    ),
                ),
            ],
            options={
                "verbose_name": "作業員",
                "verbose_name_plural": "作業員",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="案件名")),
                ("address", models.TextField(verbose_name="作業場所")),
                ("start_date", models.DateField(verbose_name="開始予定日")),
                ("end_date", models.DateField(verbose_name="終了予定日")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="金額"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "下書き"),
                            ("confirmed", "確定"),
                            ("in_progress", "作業中"),
                            ("completed", "完了"),
                            ("cancelled", "キャンセル"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="詳細情報"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.customer",
                        verbose_name="顧客",
                    ),
                ),
                (
                    "project_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.projecttype",
                        verbose_name="工種",
                    ),
                ),
            ],
            options={
                "verbose_name": "案件",
                "verbose_name_plural": "案件",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="アサイン日時"
                    ),
                ),
                ("is_confirmed", models.BooleanField(default=False, verbose_name="確定")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.worker",
                        verbose_name="作業員",
                    ),
                ),
            ],
            options={
                "verbose_name": "作業員アサイン",
                "verbose_name_plural": "作業員アサイン",
                "unique_together": {("project", "worker")},
            },
        ),
    ]
