# Generated by Django 4.2.6 on 2025-09-15 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Surveyor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="調査員名")),
                ("phone", models.CharField(max_length=20, verbose_name="電話番号")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="メールアドレス"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="稼働可能")),
                (
                    "base_location",
                    models.CharField(blank=True, max_length=100, verbose_name="拠点"),
                ),
                (
                    "daily_capacity",
                    models.IntegerField(default=3, verbose_name="1日最大件数"),
                ),
                (
                    "work_start_time",
                    models.TimeField(default="09:00", verbose_name="開始時刻"),
                ),
                (
                    "work_end_time",
                    models.TimeField(default="17:00", verbose_name="終了時刻"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
            ],
            options={
                "verbose_name": "調査員",
                "verbose_name_plural": "調査員",
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="予定日時"),
                ),
                (
                    "actual_start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="実際の開始時刻"),
                ),
                (
                    "actual_end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="実際の終了時刻"),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(default=120, verbose_name="想定時間（分）"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "予定"),
                            ("in_progress", "調査中"),
                            ("completed", "完了"),
                            ("cancelled", "キャンセル"),
                            ("rescheduled", "再調整"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("normal", "通常"),
                            ("high", "高"),
                            ("urgent", "緊急"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="優先度",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                ("access_info", models.TextField(blank=True, verbose_name="現場アクセス情報")),
                (
                    "is_survey_completed",
                    models.BooleanField(default=False, verbose_name="調査完了"),
                ),
                ("site_condition", models.TextField(blank=True, verbose_name="現場状況")),
                (
                    "customer_requirements",
                    models.TextField(blank=True, verbose_name="顧客要望"),
                ),
                ("technical_notes", models.TextField(blank=True, verbose_name="技術メモ")),
                (
                    "additional_work_needed",
                    models.BooleanField(default=False, verbose_name="追加作業要否"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "surveyor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.surveyor",
                        verbose_name="調査員",
                    ),
                ),
            ],
            options={
                "verbose_name": "現地調査",
                "verbose_name_plural": "現地調査",
                "ordering": ["scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="SurveyRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                (
                    "optimized_order",
                    models.JSONField(default=list, verbose_name="最適化順序"),
                ),
                (
                    "total_travel_time",
                    models.IntegerField(default=0, verbose_name="総移動時間（分）"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "surveyor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.surveyor",
                        verbose_name="調査員",
                    ),
                ),
                (
                    "surveys",
                    models.ManyToManyField(to="projects.survey", verbose_name="調査案件"),
                ),
            ],
            options={
                "verbose_name": "調査ルート",
                "verbose_name_plural": "調査ルート",
                "unique_together": {("date", "surveyor")},
            },
        ),
        migrations.CreateModel(
            name="SurveyAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                ("start_time", models.TimeField(verbose_name="開始時刻")),
                ("end_time", models.TimeField(verbose_name="終了時刻")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="稼働可能"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "surveyor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.surveyor",
                        verbose_name="調査員",
                    ),
                ),
            ],
            options={
                "verbose_name": "調査員稼働時間",
                "verbose_name_plural": "調査員稼働時間",
                "unique_together": {("surveyor", "date")},
            },
        ),
    ]
