# Generated by Django 4.2.6 on 2025-09-15 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_surveyor_survey_surveyroute_surveyavailability"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actual_area",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="実測面積（㎡）"
                    ),
                ),
                (
                    "access_notes",
                    models.TextField(
                        help_text="駐車場、搬入経路、エレベーター等", verbose_name="アクセス情報"
                    ),
                ),
                (
                    "special_requirements",
                    models.TextField(
                        blank=True, help_text="家具移動、養生、時間制約等", verbose_name="特殊要件"
                    ),
                ),
                (
                    "wall_condition",
                    models.CharField(
                        choices=[
                            ("excellent", "優良"),
                            ("good", "良好"),
                            ("fair", "普通"),
                            ("poor", "不良"),
                            ("unknown", "未確認"),
                        ],
                        default="good",
                        max_length=20,
                        verbose_name="壁面状態",
                    ),
                ),
                (
                    "floor_condition",
                    models.CharField(
                        choices=[
                            ("excellent", "優良"),
                            ("good", "良好"),
                            ("fair", "普通"),
                            ("poor", "不良"),
                            ("unknown", "未確認"),
                        ],
                        default="good",
                        max_length=20,
                        verbose_name="床面状態",
                    ),
                ),
                (
                    "ceiling_condition",
                    models.CharField(
                        choices=[
                            ("excellent", "優良"),
                            ("good", "良好"),
                            ("fair", "普通"),
                            ("poor", "不良"),
                            ("unknown", "未確認"),
                        ],
                        default="good",
                        max_length=20,
                        verbose_name="天井状態",
                    ),
                ),
                (
                    "electrical_condition",
                    models.CharField(
                        choices=[
                            ("excellent", "優良"),
                            ("good", "良好"),
                            ("fair", "普通"),
                            ("poor", "不良"),
                            ("unknown", "未確認"),
                        ],
                        default="good",
                        max_length=20,
                        verbose_name="電気設備",
                    ),
                ),
                (
                    "room_temperature",
                    models.IntegerField(blank=True, null=True, verbose_name="室温（℃）"),
                ),
                (
                    "humidity_level",
                    models.CharField(
                        choices=[("low", "低"), ("normal", "普通"), ("high", "高")],
                        default="normal",
                        max_length=20,
                        verbose_name="湿度",
                    ),
                ),
                (
                    "ventilation_quality",
                    models.CharField(
                        choices=[("poor", "悪い"), ("fair", "普通"), ("good", "良い")],
                        default="fair",
                        max_length=20,
                        verbose_name="換気状況",
                    ),
                ),
                ("surveyor_notes", models.TextField(verbose_name="調査員メモ")),
                ("voice_memo_url", models.URLField(blank=True, verbose_name="音声メモURL")),
                (
                    "estimated_work_days",
                    models.IntegerField(default=1, verbose_name="想定作業日数"),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "易"),
                            ("normal", "普通"),
                            ("hard", "困難"),
                            ("very_hard", "非常に困難"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="作業難易度",
                    ),
                ),
                (
                    "is_ready_for_assignment",
                    models.BooleanField(default=False, verbose_name="職人アサイン準備完了"),
                ),
                (
                    "assignment_notes",
                    models.TextField(blank=True, verbose_name="職人選定向けメモ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "survey",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.survey",
                        verbose_name="調査",
                    ),
                ),
            ],
            options={
                "verbose_name": "調査記録",
                "verbose_name_plural": "調査記録",
            },
        ),
        migrations.CreateModel(
            name="WorkerNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("survey_completed", "調査完了"),
                            ("report_ready", "レポート準備完了"),
                            ("urgent_assignment", "緊急アサイン要請"),
                            ("schedule_change", "スケジュール変更"),
                        ],
                        max_length=30,
                        verbose_name="通知種別",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="タイトル")),
                ("message", models.TextField(verbose_name="メッセージ")),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="宛先メール"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "未読"),
                            ("read", "既読"),
                            ("responded", "対応済み"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="送信日時"),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="既読日時"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "survey_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.surveyreport",
                        verbose_name="調査記録",
                    ),
                ),
            ],
            options={
                "verbose_name": "職人選定通知",
                "verbose_name_plural": "職人選定通知",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SurveyTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="テンプレート名")),
                (
                    "default_photos",
                    models.JSONField(default=list, verbose_name="標準撮影箇所"),
                ),
                (
                    "checklist_items",
                    models.JSONField(default=list, verbose_name="チェック項目"),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(default=120, verbose_name="標準調査時間（分）"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "project_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.projecttype",
                        verbose_name="工種",
                    ),
                ),
            ],
            options={
                "verbose_name": "調査テンプレート",
                "verbose_name_plural": "調査テンプレート",
            },
        ),
        migrations.CreateModel(
            name="SurveyPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="survey_photos/%Y/%m/%d/", verbose_name="写真"
                    ),
                ),
                ("description", models.CharField(max_length=200, verbose_name="説明")),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("overview", "全景"),
                            ("living", "リビング"),
                            ("kitchen", "キッチン"),
                            ("bedroom", "寝室"),
                            ("bathroom", "バスルーム"),
                            ("toilet", "トイレ"),
                            ("entrance", "玄関"),
                            ("balcony", "ベランダ"),
                            ("wall", "壁面詳細"),
                            ("ceiling", "天井詳細"),
                            ("floor", "床面詳細"),
                            ("damage", "損傷箇所"),
                            ("electrical", "電気設備"),
                            ("plumbing", "配管"),
                            ("other", "その他"),
                        ],
                        max_length=20,
                        verbose_name="撮影場所",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=10,
                        null=True,
                        verbose_name="緯度",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=11,
                        null=True,
                        verbose_name="経度",
                    ),
                ),
                ("is_before", models.BooleanField(default=True, verbose_name="施工前写真")),
                (
                    "upload_order",
                    models.IntegerField(default=0, verbose_name="アップロード順序"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="撮影日時"),
                ),
                (
                    "survey_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="projects.surveyreport",
                        verbose_name="調査記録",
                    ),
                ),
            ],
            options={
                "verbose_name": "調査写真",
                "verbose_name_plural": "調査写真",
                "ordering": ["upload_order", "created_at"],
            },
        ),
    ]
