# Generated by Django 4.2.6 on 2025-09-15 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_surveyreport_workernotification_surveytemplate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inquiry", "打診中"),
                            ("confirmed", "確定"),
                            ("declined", "辞退"),
                            ("in_progress", "作業中"),
                            ("completed", "完了"),
                            ("cancelled", "キャンセル"),
                        ],
                        default="inquiry",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("normal", "通常"),
                            ("high", "高"),
                            ("urgent", "緊急"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="優先度",
                    ),
                ),
                ("scheduled_start_date", models.DateField(verbose_name="予定開始日")),
                ("scheduled_end_date", models.DateField(verbose_name="予定終了日")),
                ("estimated_hours", models.IntegerField(verbose_name="想定作業時間")),
                (
                    "offered_rate",
                    models.DecimalField(
                        decimal_places=0, max_digits=8, verbose_name="提示単価（円）"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        verbose_name="総額（円）",
                    ),
                ),
                ("inquiry_message", models.TextField(verbose_name="打診メッセージ")),
                (
                    "response_message",
                    models.TextField(blank=True, verbose_name="返答メッセージ"),
                ),
                (
                    "response_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="返答日時"),
                ),
                (
                    "contact_method",
                    models.CharField(
                        choices=[("phone", "電話"), ("line", "LINE"), ("email", "メール")],
                        default="phone",
                        max_length=20,
                        verbose_name="連絡手段",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="打診日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.surveyor",
                        verbose_name="アサイン担当者",
                    ),
                ),
            ],
            options={
                "verbose_name": "案件アサイン",
                "verbose_name_plural": "案件アサイン",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Craftsman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="職人名")),
                ("phone", models.CharField(max_length=20, verbose_name="電話番号")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="メールアドレス"
                    ),
                ),
                (
                    "line_id",
                    models.CharField(blank=True, max_length=50, verbose_name="LINE ID"),
                ),
                (
                    "skill_level",
                    models.IntegerField(
                        choices=[
                            (1, "初級"),
                            (2, "中級"),
                            (3, "上級"),
                            (4, "熟練"),
                            (5, "マスター"),
                        ],
                        default=2,
                        verbose_name="技能レベル",
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=0, max_digits=6, verbose_name="時給（円）"
                    ),
                ),
                (
                    "coverage_areas",
                    models.TextField(help_text="カンマ区切りで入力", verbose_name="対応エリア"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="稼働可能")),
                ("bio", models.TextField(blank=True, verbose_name="自己紹介・実績")),
                ("total_jobs", models.IntegerField(default=0, verbose_name="総作業件数")),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=3, verbose_name="平均評価"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "specialties",
                    models.ManyToManyField(
                        to="projects.projecttype", verbose_name="得意工種"
                    ),
                ),
            ],
            options={
                "verbose_name": "職人",
                "verbose_name_plural": "職人",
                "ordering": ["-average_rating", "hourly_rate"],
            },
        ),
        migrations.CreateModel(
            name="CraftsmanRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "technical_skill",
                    models.IntegerField(
                        choices=[(1, "1点"), (2, "2点"), (3, "3点"), (4, "4点"), (5, "5点")],
                        verbose_name="技術力",
                    ),
                ),
                (
                    "punctuality",
                    models.IntegerField(
                        choices=[(1, "1点"), (2, "2点"), (3, "3点"), (4, "4点"), (5, "5点")],
                        verbose_name="時間厳守",
                    ),
                ),
                (
                    "communication",
                    models.IntegerField(
                        choices=[(1, "1点"), (2, "2点"), (3, "3点"), (4, "4点"), (5, "5点")],
                        verbose_name="コミュニケーション",
                    ),
                ),
                (
                    "work_quality",
                    models.IntegerField(
                        choices=[(1, "1点"), (2, "2点"), (3, "3点"), (4, "4点"), (5, "5点")],
                        verbose_name="作業品質",
                    ),
                ),
                (
                    "overall_rating",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="総合評価"
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="コメント")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="評価日時"),
                ),
                (
                    "assignment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.assignment",
                        verbose_name="案件",
                    ),
                ),
                (
                    "craftsman",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.craftsman",
                        verbose_name="職人",
                    ),
                ),
                (
                    "surveyor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.surveyor",
                        verbose_name="評価者",
                    ),
                ),
            ],
            options={
                "verbose_name": "職人評価",
                "verbose_name_plural": "職人評価",
            },
        ),
        migrations.AddField(
            model_name="assignment",
            name="craftsman",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.craftsman",
                verbose_name="職人",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
                verbose_name="案件",
            ),
        ),
        migrations.CreateModel(
            name="CraftsmanSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="稼働可能"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "assigned_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.project",
                        verbose_name="アサイン済み案件",
                    ),
                ),
                (
                    "craftsman",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.craftsman",
                        verbose_name="職人",
                    ),
                ),
            ],
            options={
                "verbose_name": "職人スケジュール",
                "verbose_name_plural": "職人スケジュール",
                "ordering": ["date", "craftsman"],
                "unique_together": {("craftsman", "date")},
            },
        ),
    ]
