# Generated by Django 4.2.6 on 2025-09-15 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0004_assignment_craftsman_craftsmanrating_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="業者名")),
                (
                    "contact_person",
                    models.CharField(max_length=50, verbose_name="担当者名"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="電話番号")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="メールアドレス"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="住所")),
                (
                    "payment_terms",
                    models.CharField(blank=True, max_length=100, verbose_name="支払条件"),
                ),
                ("delivery_area", models.TextField(blank=True, verbose_name="配送エリア")),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "specialties",
                    models.ManyToManyField(
                        to="projects.projecttype", verbose_name="取扱工種"
                    ),
                ),
            ],
            options={
                "verbose_name": "資材業者",
                "verbose_name_plural": "資材業者",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MaterialOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(max_length=20, unique=True, verbose_name="発注番号"),
                ),
                ("order_details", models.TextField(verbose_name="発注内容")),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="見積金額",
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="実際金額",
                    ),
                ),
                (
                    "order_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="発注日"),
                ),
                (
                    "delivery_date",
                    models.DateField(blank=True, null=True, verbose_name="納期"),
                ),
                (
                    "actual_delivery_date",
                    models.DateField(blank=True, null=True, verbose_name="実際納期"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "下書き"),
                            ("ordered", "発注済"),
                            ("delivered", "納品済"),
                            ("cancelled", "キャンセル"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "delivery_address",
                    models.TextField(blank=True, verbose_name="納品先住所"),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=50, verbose_name="現場担当者"),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="現場連絡先"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "ordered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="発注者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_orders",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.supplier",
                        verbose_name="業者",
                    ),
                ),
            ],
            options={
                "verbose_name": "資材発注",
                "verbose_name_plural": "資材発注",
                "ordering": ["-created_at"],
            },
        ),
    ]
