# Generated by Django 4.2.6 on 2025-09-15 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0005_supplier_materialorder"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="基準コスト"
                    ),
                ),
                (
                    "margin_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="マージン率(%)"
                    ),
                ),
                (
                    "margin_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="マージン金額"
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="最終請求額"
                    ),
                ),
                (
                    "pricing_stage",
                    models.CharField(
                        choices=[
                            ("estimate", "見積もり段階"),
                            ("contract", "受注段階"),
                            ("final", "確定"),
                        ],
                        max_length=20,
                        verbose_name="価格設定段階",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_history",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "set_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="設定者",
                    ),
                ),
            ],
            options={
                "verbose_name": "案件価格設定",
                "verbose_name_plural": "案件価格設定",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "craftsman_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="職人費用"
                    ),
                ),
                (
                    "material_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="資材費"
                    ),
                ),
                (
                    "transportation_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="交通費"
                    ),
                ),
                (
                    "survey_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="調査費"
                    ),
                ),
                (
                    "other_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="その他経費"
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="総コスト"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_cost",
                        to="projects.project",
                        verbose_name="案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "案件コスト",
                "verbose_name_plural": "案件コスト",
            },
        ),
        migrations.CreateModel(
            name="PricingAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("created", "作成"),
                            ("updated", "更新"),
                            ("deactivated", "無効化"),
                        ],
                        max_length=20,
                        verbose_name="変更種別",
                    ),
                ),
                ("old_values", models.JSONField(default=dict, verbose_name="変更前値")),
                ("new_values", models.JSONField(default=dict, verbose_name="変更後値")),
                ("reason", models.TextField(blank=True, verbose_name="変更理由")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="変更日時"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="変更者",
                    ),
                ),
                (
                    "pricing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="projects.projectpricing",
                        verbose_name="価格設定",
                    ),
                ),
            ],
            options={
                "verbose_name": "価格設定変更履歴",
                "verbose_name_plural": "価格設定変更履歴",
                "ordering": ["-created_at"],
            },
        ),
    ]
