# Generated by Django 4.2.6 on 2025-09-15 03:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0006_projectpricing_projectcost_pricingauditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConstructionProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateTimeField(auto_now_add=True)),
                (
                    "progress_rate",
                    models.IntegerField(
                        help_text="進捗率（0-100%）",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("work_description", models.TextField(verbose_name="作業内容")),
                ("issues", models.TextField(blank=True, verbose_name="問題・課題")),
                ("next_plan", models.TextField(blank=True, verbose_name="翌日予定")),
                (
                    "reported_by",
                    models.CharField(
                        choices=[
                            ("line", "LINE"),
                            ("phone", "電話"),
                            ("direct", "直接入力"),
                            ("email", "メール"),
                        ],
                        default="direct",
                        max_length=20,
                        verbose_name="報告手段",
                    ),
                ),
                (
                    "weather",
                    models.CharField(blank=True, max_length=50, verbose_name="天候"),
                ),
                ("worker_count", models.IntegerField(default=1, verbose_name="作業人数")),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="開始時刻"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="終了時刻"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "craftsman",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_reports",
                        to="projects.craftsman",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="construction_progress",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "施工進捗",
                "verbose_name_plural": "施工進捗",
                "ordering": ["-report_date"],
            },
        ),
        migrations.AlterModelOptions(
            name="pricingauditlog",
            options={"verbose_name": "価格設定変更履歴", "verbose_name_plural": "価格設定変更履歴"},
        ),
        migrations.CreateModel(
            name="ProjectIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("additional_work", "追加工事"),
                            ("quality", "品質問題"),
                            ("complaint", "顧客クレーム"),
                            ("delay", "工期遅れ"),
                            ("safety", "安全問題"),
                            ("materials", "資材問題"),
                            ("weather", "天候問題"),
                            ("other", "その他"),
                        ],
                        max_length=20,
                        verbose_name="問題種別",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="問題タイトル")),
                ("description", models.TextField(verbose_name="詳細説明")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("critical", "緊急"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="優先度",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "対応中"),
                            ("in_progress", "作業中"),
                            ("resolved", "解決済"),
                            ("escalated", "エスカレーション"),
                            ("closed", "クローズ"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="対応状況",
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        verbose_name="追加費用見込み",
                    ),
                ),
                ("resolution", models.TextField(blank=True, verbose_name="解決内容")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_issues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="担当者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="projects.project",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_issues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="報告者",
                    ),
                ),
            ],
            options={
                "verbose_name": "プロジェクト問題",
                "verbose_name_plural": "プロジェクト問題",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completion_date",
                    models.DateField(blank=True, null=True, verbose_name="完了日"),
                ),
                (
                    "customer_check_date",
                    models.DateField(blank=True, null=True, verbose_name="顧客確認日"),
                ),
                (
                    "approval_date",
                    models.DateField(blank=True, null=True, verbose_name="承認日"),
                ),
                (
                    "final_photos_submitted",
                    models.BooleanField(default=False, verbose_name="完了写真提出済み"),
                ),
                (
                    "customer_signature",
                    models.BooleanField(default=False, verbose_name="顧客サイン済み"),
                ),
                (
                    "payment_processed",
                    models.BooleanField(default=False, verbose_name="支払い処理済み"),
                ),
                ("completion_notes", models.TextField(blank=True, verbose_name="完了備考")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "施工中"),
                            ("completed", "完了"),
                            ("customer_check", "顧客確認中"),
                            ("approved", "承認済"),
                            ("payment_pending", "支払い待ち"),
                            ("closed", "クローズ"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="完了ステータス",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completion",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "プロジェクト完了",
                "verbose_name_plural": "プロジェクト完了",
            },
        ),
        migrations.CreateModel(
            name="ProgressPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="construction_photos/%Y/%m/")),
                ("description", models.CharField(max_length=100, verbose_name="写真説明")),
                (
                    "photo_type",
                    models.CharField(
                        choices=[
                            ("before", "施工前"),
                            ("during", "施工中"),
                            ("after", "完了"),
                            ("issue", "問題箇所"),
                            ("safety", "安全対策"),
                            ("materials", "資材状況"),
                        ],
                        default="during",
                        max_length=20,
                        verbose_name="写真種別",
                    ),
                ),
                ("taken_at", models.DateTimeField(auto_now_add=True)),
                (
                    "progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="projects.constructionprogress",
                    ),
                ),
            ],
            options={
                "verbose_name": "進捗写真",
                "verbose_name_plural": "進捗写真",
                "ordering": ["-taken_at"],
            },
        ),
    ]
