# Generated by Django 4.2.6 on 2025-09-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "projects",
            "0007_constructionprogress_alter_pricingauditlog_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="requires_survey",
            field=models.BooleanField(default=False, verbose_name="現調必要"),
        ),
    ]
