# Generated by Django 4.2.6 on 2025-09-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_project_requires_survey"),
    ]

    operations = [
        migrations.AddField(
            model_name="constructionprogress",
            name="additional_items",
            field=models.JSONField(blank=True, default=dict, verbose_name="追加項目"),
        ),
    ]
