# Generated by Django 4.2.6 on 2025-09-21 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_add_additional_items_to_progress"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectEditSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=64, verbose_name="セッションID")),
                (
                    "user_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="ユーザーID"
                    ),
                ),
                (
                    "additional_items",
                    models.JSONField(blank=True, default=dict, verbose_name="追加項目"),
                ),
                ("edit_mode", models.BooleanField(default=False, verbose_name="編集モード")),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, verbose_name="最終アクティビティ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_sessions",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "プロジェクト編集セッション",
                "verbose_name_plural": "プロジェクト編集セッション",
                "ordering": ["-last_activity"],
                "unique_together": {("project", "session_id")},
            },
        ),
    ]
