# Generated by Django 4.2.6 on 2025-10-31 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0022_commentattachment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectprogressstep",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="projectprogressstep",
            name="project",
        ),
        migrations.RemoveField(
            model_name="projectprogressstep",
            name="template",
        ),
        migrations.DeleteModel(
            name="ProgressStepTemplate",
        ),
        migrations.DeleteModel(
            name="ProjectProgressStep",
        ),
    ]
