# Generated by Django 5.2.6 on 2025-09-21 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("order_management", "0007_alter_contractor_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_date", models.DateField(verbose_name="予定日")),
                ("scheduled_start_time", models.TimeField(verbose_name="開始予定時刻")),
                (
                    "estimated_duration",
                    models.IntegerField(default=120, verbose_name="予定所要時間（分）"),
                ),
                (
                    "actual_start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="実際の開始時刻"),
                ),
                (
                    "actual_end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="実際の終了時刻"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "予定"),
                            ("in_progress", "進行中"),
                            ("completed", "完了"),
                            ("cancelled", "キャンセル"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order_management.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "surveyor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="調査員",
                    ),
                ),
            ],
            options={
                "verbose_name": "現地調査",
                "verbose_name_plural": "現地調査",
                "ordering": ["-scheduled_date", "-scheduled_start_time"],
            },
        ),
        migrations.CreateModel(
            name="SurveyDamage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "damage_type",
                    models.CharField(
                        choices=[
                            ("stain_discoloration", "汚れ・変色"),
                            ("tear_peel", "破れ・剥がれ"),
                            ("nail_holes", "釘穴・画鋲穴"),
                            ("large_holes", "大きな穴・ネジ穴"),
                            ("mold_stain", "カビ・水染み"),
                            ("tobacco_stain", "タバコヤニ"),
                            ("oil_stain", "油汚れ"),
                        ],
                        max_length=30,
                        verbose_name="損傷種別",
                    ),
                ),
                ("has_dents", models.BooleanField(default=False, verbose_name="凹みあり")),
                ("dent_count", models.IntegerField(default=0, verbose_name="凹み個数")),
                ("description", models.TextField(blank=True, verbose_name="詳細説明")),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="damages",
                        to="surveys.survey",
                        verbose_name="調査",
                    ),
                ),
            ],
            options={
                "verbose_name": "損傷調査",
                "verbose_name_plural": "損傷調査",
            },
        ),
        migrations.CreateModel(
            name="SurveyPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo_type",
                    models.CharField(
                        choices=[
                            ("room_overview", "部屋全景"),
                            ("damage_detail", "損傷箇所"),
                            ("dent_detail", "凹み詳細"),
                        ],
                        max_length=20,
                        verbose_name="写真種別",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="survey_photos/%Y/%m/%d/", verbose_name="写真"
                    ),
                ),
                (
                    "caption",
                    models.CharField(blank=True, max_length=200, verbose_name="キャプション"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="アップロード日時"),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="surveys.survey",
                        verbose_name="調査",
                    ),
                ),
            ],
            options={
                "verbose_name": "調査写真",
                "verbose_name_plural": "調査写真",
            },
        ),
        migrations.CreateModel(
            name="SurveyRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_name", models.CharField(max_length=100, verbose_name="部屋名")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="surveys.survey",
                        verbose_name="調査",
                    ),
                ),
            ],
            options={
                "verbose_name": "調査部屋",
                "verbose_name_plural": "調査部屋",
            },
        ),
        migrations.CreateModel(
            name="SurveyWall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("north", "北壁"),
                            ("south", "南壁"),
                            ("east", "東壁"),
                            ("west", "西壁"),
                            ("ceiling", "天井"),
                        ],
                        max_length=20,
                        verbose_name="壁面方向",
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=1, max_digits=5, verbose_name="長さ(m)"
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=1, max_digits=5, verbose_name="高さ(m)"
                    ),
                ),
                (
                    "opening_area",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=5,
                        verbose_name="開口部面積(㎡)",
                    ),
                ),
                (
                    "foundation_type",
                    models.CharField(
                        choices=[
                            ("gypsum_board", "石膏ボード"),
                            ("concrete", "コンクリート"),
                            ("plywood", "合板"),
                            ("other", "その他"),
                        ],
                        max_length=20,
                        verbose_name="下地種別",
                    ),
                ),
                (
                    "foundation_condition",
                    models.CharField(
                        choices=[("good", "良好"), ("needs_repair", "補修必要")],
                        max_length=20,
                        verbose_name="下地状態",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="walls",
                        to="surveys.surveyroom",
                        verbose_name="部屋",
                    ),
                ),
            ],
            options={
                "verbose_name": "壁面調査",
                "verbose_name_plural": "壁面調査",
            },
        ),
    ]
