# Generated by Django 5.2.6 on 2025-09-22 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Surveyor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="調査員名")),
                (
                    "employee_id",
                    models.CharField(max_length=20, unique=True, verbose_name="社員番号"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="メールアドレス"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="電話番号"),
                ),
                (
                    "department",
                    models.CharField(blank=True, max_length=50, verbose_name="所属部署"),
                ),
                ("specialties", models.TextField(blank=True, verbose_name="専門分野")),
                ("certifications", models.TextField(blank=True, verbose_name="保有資格")),
                ("is_active", models.BooleanField(default=True, verbose_name="稼働中")),
                (
                    "hire_date",
                    models.DateField(blank=True, null=True, verbose_name="入社日"),
                ),
                (
                    "experience_years",
                    models.IntegerField(default=0, verbose_name="調査経験年数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="surveyor_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザーアカウント",
                    ),
                ),
            ],
            options={
                "verbose_name": "調査員",
                "verbose_name_plural": "調査員一覧",
                "ordering": ["-is_active", "name"],
            },
        ),
        migrations.AlterField(
            model_name="survey",
            name="surveyor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_surveys",
                to="surveys.surveyor",
                verbose_name="調査員",
            ),
        ),
    ]
