# Generated by Django 5.2.6 on 2025-09-23 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0002_surveyor_alter_survey_surveyor"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyWorkflowStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("room_setup", "部屋設定"),
                            ("wall_measurement", "壁面測定"),
                            ("condition_check", "状態確認"),
                            ("photo_capture", "写真撮影"),
                            ("damage_assessment", "損傷評価"),
                            ("completion_check", "完了確認"),
                        ],
                        max_length=20,
                        verbose_name="ステップ種別",
                    ),
                ),
                ("step_number", models.IntegerField(verbose_name="ステップ番号")),
                ("title", models.CharField(max_length=100, verbose_name="ステップタイトル")),
                ("description", models.TextField(verbose_name="説明")),
                (
                    "instruction_html",
                    models.TextField(blank=True, verbose_name="詳細手順（HTML）"),
                ),
                (
                    "required_photos",
                    models.IntegerField(default=0, verbose_name="必要写真枚数"),
                ),
                (
                    "estimated_minutes",
                    models.IntegerField(default=5, verbose_name="予想所要時間（分）"),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(default=True, verbose_name="必須ステップ"),
                ),
            ],
            options={
                "verbose_name": "ワークフローステップ",
                "verbose_name_plural": "ワークフローステップ",
                "ordering": ["step_number"],
            },
        ),
        migrations.AddField(
            model_name="surveyphoto",
            name="wall",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="surveys.surveywall",
                verbose_name="対象壁面",
            ),
        ),
        migrations.AlterField(
            model_name="surveyphoto",
            name="photo_type",
            field=models.CharField(
                choices=[
                    ("room_overview", "部屋全景"),
                    ("damage_detail", "損傷箇所"),
                    ("dent_detail", "凹み詳細"),
                    ("wall_condition", "壁面状態"),
                    ("measurement_reference", "測定参考"),
                ],
                max_length=30,
                verbose_name="写真種別",
            ),
        ),
        migrations.CreateModel(
            name="SurveyStepProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "未開始"),
                            ("in_progress", "進行中"),
                            ("completed", "完了"),
                            ("skipped", "スキップ"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="開始時刻"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完了時刻"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="メモ")),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="ステップデータ"),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveys.surveyroom",
                        verbose_name="対象部屋",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_progress",
                        to="surveys.survey",
                        verbose_name="調査",
                    ),
                ),
                (
                    "wall",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveys.surveywall",
                        verbose_name="対象壁面",
                    ),
                ),
                (
                    "workflow_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveys.surveyworkflowstep",
                        verbose_name="ワークフローステップ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ステップ進捗",
                "verbose_name_plural": "ステップ進捗",
                "unique_together": {("survey", "workflow_step", "room", "wall")},
            },
        ),
    ]
