# Generated by Django 5.2.6 on 2025-09-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0003_surveyworkflowstep_surveyphoto_wall_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyworkflowstep",
            name="step_type",
            field=models.CharField(
                choices=[
                    ("survey_overview", "調査概要"),
                    ("room_setup", "部屋・壁面管理"),
                    ("wall_measurement", "壁面測定"),
                    ("condition_check", "状態確認"),
                    ("photo_capture", "写真撮影"),
                    ("damage_assessment", "損傷評価"),
                    ("completion_check", "完了確認"),
                ],
                max_length=20,
                verbose_name="ステップ種別",
            ),
        ),
    ]
