# Generated by Django 5.2.6 on 2025-09-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0004_alter_surveyworkflowstep_step_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="approval_notes",
            field=models.TextField(blank=True, verbose_name="承認コメント"),
        ),
        migrations.AddField(
            model_name="survey",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="承認日時"),
        ),
        migrations.AddField(
            model_name="survey",
            name="approved_by",
            field=models.CharField(blank=True, max_length=100, verbose_name="承認者"),
        ),
        migrations.AlterField(
            model_name="survey",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "予定"),
                    ("in_progress", "進行中"),
                    ("completed", "完了"),
                    ("pending_approval", "承認待ち"),
                    ("approved", "承認済み"),
                    ("rejected", "差し戻し"),
                    ("cancelled", "キャンセル"),
                ],
                default="scheduled",
                max_length=20,
                verbose_name="ステータス",
            ),
        ),
    ]
